#!/bin/bash
#install Persepolis Download Manager
clear screen
echo "############################################################"
echo "#### Welcome to Persepolis Download Manager installation ###"
echo "################### Version 2.2 Unstable ###################"
echo "############################################################"

echo "Checking dependencies"
aria2c --version 1>/dev/null
if [ "$?" -ne "0" ];then
    echo "aria2c not installed"
    echo "Installation Failed!"
    exit
fi
python3 --version 1>/dev/null
if [ "$?" -ne "0" ];then
    echo "python3 not installed"
    echo "Installation Failed!"
    exit
fi

install_path=`pwd`
cd "$install_path"
chmod +x "./checkpyqt.py"

./checkpyqt.py
if [ "$?" -ne "0" ];then
    echo "pyqt5 not installed"
    echo "Installation Failed!"
    exit
fi

notify-send --version 1>/dev/null
if [ "$?" -ne "0" ];then
    echo "libnotify-bin not installed"
    echo "Installation Failed!"
    exit
fi

paplay --version 1>/dev/null
if [ "$?" -ne "0" ];then
    echo "vorbis-tools not installed"
    echo "Installation Failed!"
    exit
fi


program_path="/usr/share/persepolis"
exec_path='/usr/bin/'
chmod +x "./files/persepolis-download-manager"
chmod +x "./persepolis"
chmod +x "./Persepolis Download Manager.desktop"
chmod +x "./compatibility.py"
mkdir "$HOME/.fonts" 2>/dev/null 
cp "./Ubuntu.ttf" "$HOME/.fonts"
sudo rm -rf "$program_path"
sudo mkdir -p "$program_path"
sudo cp -rf  ./files/* "$program_path/"
sudo cp -rf "./persepolis" "$exec_path"
sudo cp -rf "./Persepolis Download Manager.desktop" "/usr/share/applications/"
sudo cp -rf "./files/icon.svg" "/usr/share/pixmaps/persepolis.svg"
rm -rf "$HOME/.config/persepolis_download_manager/setting"
rm -rf "$HOME/.config/persepolis_download_manager/windows_size"
if [ "$?" -eq "0" ];then
    ./compatibility.py
    echo "Installation compeleted!"
else
    echo "Installation Failed"
fi
exit



