#!/bin/bash

python3 pyinstaller/pyinstaller.py files/Persepolis\ Download\ Manager -w -i icon.icns
cp aria2c 'dist/Persepolis Download Manager.app/Contents/MacOS/'
cp Info.plist 'dist/Persepolis Download Manager.app/Contents/'
mv 'dist/Persepolis Download Manager.app' .
