#!/bin/bash
echo "***********************************"
echo "***********************************"
echo "****Persepolis Download Manager****"
echo "****  Version : 2.0.2 Unstable ****"
echo "***********************************"
echo "***********************************"

run_times=`ps -A|grep "persepolis-down"|wc -l`
echo $run_times
cd "/usr/share/persepolis"
if [ "$run_times" -eq "0" ];then
    exec ./persepolis-download-manager "$@" --execute yes  2>/tmp/persepolis_error 
else
    exec ./persepolis-download-manager "$@" --execute no 
fi
exit 


