#!/bin/bash

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


sudo rm -rf /usr/share/persepolis
sudo rm -rf /usr/bin/persepolis
sudo rm -rf /usr/share/pixmaps/persepolis.svg
sudo rm -rf "/usr/share/applications/Persepolis Download Manager.desktop"
sudo rm -rf "$HOME/.config/persepolis_download_manager/"
sudo rm -rf "/usr/share/man/man1/persepolis.1"

