#!/bin/bash
gid="$1"
shutdown_notification_file="/tmp/persepolis/shutdown/$gid"
echo "wait" > $shutdown_notification_file
shutdown_notification="wait"
while [ "$shutdown_notification" == "wait" ];do
    sleep 1 
    shutdown_notification=`cat "$shutdown_notification_file"`
done

if [ "$shutdown_notification" == "shutdown" ];then
    sleep 20 
    echo "shutdown"
    poweroff
else
    exit
fi
